<a href="https://colab.research.google.com/github/Pritesh1703/ml-journey/blob/main/PCA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
'''
Building PCA Algorithm from Scratch without using any library
PCA- Principal component analysis

- Using here for dimensionality reduction
- Create your own data using some mean and variance(optionla.You can use existing data if you have)
-Plot and visualise your data
- Centre the mean(standard scaling using unit variance and zero mean)
- Find covariance matrix
- Find eigen value and eigen vector
- If you want to reduce n dimensions to 2d, then chose top 2 eigen vectors corresponding to top 2 eigen Values which will be your principal component
- Now find the projections of all datapoints on the 2 principal components using dot product
- Now you get data with reduced features without losing much information
'''

'\nBuilding PCA Algorithm from Scratch without using any library\nPCA- Principal component analysis\n\n- Using here for dimensionality reduction\n- Create your own data using some mean and variance(optionla.You can use existing data if you have)\n-Plot and visualise your data\n- Centre the mean(standard scaling using unit variance and zero mean)\n- Find covariance matrix\n- Find eigen value and eigen vector\n- If you want to reduce n dimensions to 2d, then chose top 2 eigen vectors corresponding to top 2 eigen Values which will be your principal component\n- Now find the projections of all datapoints on the 2 principal components using dot product\n- Now you get data with reduced features without losing much information\n'

In [5]:
import numpy as np
import pandas as pd

mu1=np.array([0,0,0])
cov1=np.array([[1,0,0],[0,1,0],[0,0,1]])
sample1= np.random.multivariate_normal(mu1,cov1,20)

df1=pd.DataFrame(sample1,columns=['feature1','feature2','feature3'])
df1['target']=1

mu2=np.array([1,1,1])
cov2=np.array([[1,0,0],[0,1,0],[0,0,1]])
sample2=np.random.multivariate_normal(mu2,cov2,20)

df2=pd.DataFrame(sample2,columns=['feature1','feature2','feature3'])
df2['target']=0

df1= pd.concat([df1,df2],ignore_index=True)

In [ ]:
df1.head()

   feature1  feature2  feature3  target
0 -0.962032 -0.259406 -0.593724       1
1 -1.505742 -1.543650 -0.221272       1
2  1.114662  0.811321  1.129488       1
3  1.815675 -0.749548 -0.323163       1
4 -1.646402 -0.440554  0.249016       1

In [8]:

import plotly.express as px
fig = px.scatter_3d(df1 ,x=df1['feature1'], y=df1['feature2'], z=df1['feature3'],
              color=df1['target'].astype('str'))
fig.update_traces(marker=dict(size=12,
                              line=dict(width=2,
                                        color='DarkSlateGrey')),
                  selector=dict(mode='markers'))

fig.show()

In [9]:
# Standard Scaling- Unit variance, zero mean

from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()

df1.iloc[:,0:3] = scaler.fit_transform(df1.iloc[:,0:3])

In [11]:
# find a covariance matrix

cov_matrix= np.cov([df1.iloc[:,0],df1.iloc[:,1],df1.iloc[:,2]])
print(cov_matrix)

[[1.02564103 0.15302532 0.22284326]
 [0.15302532 1.02564103 0.25416358]
 [0.22284326 0.25416358 1.02564103]]

In [12]:
# find eigen value and eigen vector

eigen_values, eigen_vectors=np.linalg.eig(cov_matrix)

eigen_values [1.44834973 0.87480946 0.75376389]
eigen_vectors [[-0.53513892 -0.77640075 -0.33290871]
 [-0.56910125  0.62257551 -0.53714384]
 [-0.62429969  0.09798782  0.77501502]]

In [13]:
print("eigen_values",eigen_values)

eigen_values [1.44834973 0.87480946 0.75376389]

In [14]:

print("eigen_vectors",eigen_vectors)

eigen_vectors [[-0.53513892 -0.77640075 -0.33290871]
 [-0.56910125  0.62257551 -0.53714384]
 [-0.62429969  0.09798782  0.77501502]]

In [18]:
#lets take 2 principal components

pc=eigen_vectors[0:2]

In [21]:
# Now lets project all the original data points on these 2 principal components- data.transpose(principal component)

projections = np.dot(df1.iloc[:,0:3],pc.T)
transformed_df= pd.DataFrame(projections,columns=['PC1','PC2'])
transformed_df['target']=df1['target'].values
transformed_df.head()

        PC1       PC2  target
0  1.971759  0.450267       1
1  0.115928  0.174224       1
2  0.527710 -0.032938       1
3  1.330501  0.533431       1
4  0.031876 -1.210962       1

In [23]:

transformed_df['target'] = transformed_df['target'].astype('str')
fig = px.scatter(x=transformed_df['PC1'],
                 y=transformed_df['PC2'],
                 color=transformed_df['target'],
                 color_discrete_sequence=px.colors.qualitative.G10
                )

fig.update_traces(marker=dict(size=12,
                              line=dict(width=2,
                                        color='DarkSlateGrey')),
                  selector=dict(mode='markers'))
fig.show()